<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zhengyan.MikuMikuDance.Core\Zhengyan.MikuMikuDance.Core.csproj" />
    <ProjectReference Include="..\Zhengyan.MikuMikuDance.Formats\Zhengyan.MikuMikuDance.Formats.csproj" />
    <ProjectReference Include="..\Zhengyan.MikuMikuDance.Rendering.OpenGL\Zhengyan.MikuMikuDance.Rendering.OpenGL.csproj" />
    <ProjectReference Include="..\Zhengyan.MikuMikuDance.UI.ImGui\Zhengyan.MikuMikuDance.UI.ImGui.csproj" />
  </ItemGroup>

</Project>
